/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthenticatedEncargadoRouteImport } from './routes/_authenticated/encargado'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedReportarRouteImport } from './routes/_authenticated/reportar'
import { Route as ObjetoIdRouteImport } from './routes/objeto.$id'
import { Route as AuthenticatedReclamarIdRouteImport } from './routes/_authenticated/reclamar.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEncargadoRoute = AuthenticatedEncargadoRouteImport.update({
  id: '/encargado',
  path: '/encargado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportarRoute = AuthenticatedReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ObjetoIdRoute = ObjetoIdRouteImport.update({
  id: '/objeto/$id',
  path: '/objeto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReclamarIdRoute = AuthenticatedReclamarIdRouteImport.update({
  id: '/reclamar/$id',
  path: '/reclamar/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/buscar': typeof BuscarRoute
  '/encargado': typeof AuthenticatedEncargadoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/reportar': typeof AuthenticatedReportarRoute
  '/objeto/$id': typeof ObjetoIdRoute
  '/reclamar/$id': typeof AuthenticatedReclamarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/buscar': typeof BuscarRoute
  '/encargado': typeof AuthenticatedEncargadoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/reportar': typeof AuthenticatedReportarRoute
  '/objeto/$id': typeof ObjetoIdRoute
  '/reclamar/$id': typeof AuthenticatedReclamarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/buscar': typeof BuscarRoute
  '/_authenticated/encargado': typeof AuthenticatedEncargadoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/reportar': typeof AuthenticatedReportarRoute
  '/objeto/$id': typeof ObjetoIdRoute
  '/_authenticated/reclamar/$id': typeof AuthenticatedReclamarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avisos'
    | '/buscar'
    | '/encargado'
    | '/perfil'
    | '/reportar'
    | '/objeto/$id'
    | '/reclamar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avisos'
    | '/buscar'
    | '/encargado'
    | '/perfil'
    | '/reportar'
    | '/objeto/$id'
    | '/reclamar/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/avisos'
    | '/buscar'
    | '/_authenticated/encargado'
    | '/_authenticated/perfil'
    | '/_authenticated/reportar'
    | '/objeto/$id'
    | '/_authenticated/reclamar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvisosRoute: typeof AvisosRoute
  BuscarRoute: typeof BuscarRoute
  ObjetoIdRoute: typeof ObjetoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/encargado': {
      id: '/_authenticated/encargado'
      path: '/encargado'
      fullPath: '/encargado'
      preLoaderRoute: typeof AuthenticatedEncargadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportar': {
      id: '/_authenticated/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof AuthenticatedReportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/objeto/$id': {
      id: '/objeto/$id'
      path: '/objeto/$id'
      fullPath: '/objeto/$id'
      preLoaderRoute: typeof ObjetoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reclamar/$id': {
      id: '/_authenticated/reclamar/$id'
      path: '/reclamar/$id'
      fullPath: '/reclamar/$id'
      preLoaderRoute: typeof AuthenticatedReclamarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEncargadoRoute: typeof AuthenticatedEncargadoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedReportarRoute: typeof AuthenticatedReportarRoute
  AuthenticatedReclamarIdRoute: typeof AuthenticatedReclamarIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEncargadoRoute: AuthenticatedEncargadoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedReportarRoute: AuthenticatedReportarRoute,
  AuthenticatedReclamarIdRoute: AuthenticatedReclamarIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AvisosRoute: AvisosRoute,
  BuscarRoute: BuscarRoute,
  ObjetoIdRoute: ObjetoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
