/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ReportarRouteImport } from './routes/reportar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/buscar': typeof BuscarRoute
  '/reportar': typeof ReportarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/buscar': typeof BuscarRoute
  '/reportar': typeof ReportarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/buscar': typeof BuscarRoute
  '/reportar': typeof ReportarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avisos' | '/buscar' | '/reportar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avisos' | '/buscar' | '/reportar'
  id: '__root__' | '/' | '/avisos' | '/buscar' | '/reportar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisosRoute: typeof AvisosRoute
  BuscarRoute: typeof BuscarRoute
  ReportarRoute: typeof ReportarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisosRoute: AvisosRoute,
  BuscarRoute: BuscarRoute,
  ReportarRoute: ReportarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
